echo "windows 11 setup"
wscript rpopup.vbs
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 1/5"
echo "\ 1/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 2/5"
echo "\ 2/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 3/5"
echo "\ 3/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 4/5"
echo "\ 4/5"
echo "/ 5/5"
echo "\ 5/5"
echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "/ 5/5"
echo "\ 5/5"

echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
echo "finishing"
wscript agfgz.vbs



